FROM ubuntu:latest

RUN apt update
RUN apt install nodejs npm mongodb -y

EXPOSE 3000

ADD C:\Users\laeti\Documents\Master M1 MIAGE\Technolog\Socket_Io\td3\lecellier \Socket_Io
ENTRYPOINT node \lecellier\index.js